language: ruby
rvm: 2.4.2
sudo: false
script: "./ci/buildscript"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
deploy:
  provider: heroku
  app: travis-foundation-website
  on: master
  api_key:
    secure: Rm1cRna+t7MpnxtntICizgDlY1o111R7GeAjNVbOQf4publ5coL9vC7KoKQx/cz5jeooE9Wx/4qe83/JIXdIVtAJZEcFDuEq+mTDPFn4z3teOp6Mwlr7jT83bWSajGHeuF9Bmw1BetFJ1TwKPJEbOc8ceDnHyqEIKfZkbnatc4M=
