permalink: pretty
safe: true
exclude:
  - 'Gemfile*'
  - 'Guardfile'
  - '*.coffeescript'
  - '*.scss'
  - '*.slim'
  - 'source'
markdown: kramdown
syntax-highlighting:
  enabled: true
kramdown:
  hard_wrap: false
  input: GFM
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
sass:
  style: compressed
  sass_dir: stylesheets
